FROM pytorch/pytorch:2.7.1-cuda12.6-cudnn9-runtime
RUN apt-get update && apt-get install -y gcc g++ build-essential
RUN pip install modelscope jupyter unsloth_zoo unsloth datasets bitsandbytes -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install einx==0.3.0 omegaconf==2.3.0 soundfile==0.12.1 soxr==0.5.0.post1 librosa einops lameenc -i https://pypi.tuna.tsinghua.edu.cn/simple

WORKDIR /workspace
EXPOSE 8888
CMD ["jupyter", "notebook", "--allow-root", "--no-browser", "--ip=0.0.0.0", "--port=8888", "--NotebookApp.token=''", "--NotebookApp.password=''"]